export const USER_ADDCART_REQUEST = 'USER_ADDCART_REQUEST';
export const USER_ADDCART_SUCCESS = 'USER_ADDCART_SUCCESS';
export const USER_ADDCART_FAIL = 'USER_ADDCART_FAIL';
// Add more constants as needed

export const USER_REMOVECART_REQUEST = 'USER_REMOVECART_REQUEST';
export const USER_REMOVECART_SUCCESS = 'USER_REMOVECART_SUCCESS';
export const USER_REMOVECART_FAIL = 'USER_REMOVECART_FAIL';